version: '3'
services:
    nginxrouter_dev:
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginxrouter
        ports:
            - "3001:80"
        volumes:
            - ./nginxrouter/default_dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - webapp_dev
    webapp_dev:
        build:
            dockerfile: Dockerfile.dev
            context: ./webapp
        volumes:
            - ./webapp/src:/app/src
    cryptserver_dev:
        build:
            dockerfile: Dockerfile.dev
            context: ./cryptserver
        volumes:
            - ./cryptserver:/app
        environment:
            - FLASK_APP=server.py
            - FLASK_ENV=development
            - REDIS_HOST=redisserver_dev
    redisserver_dev:
        image: "redis:latest"


        

        

            
